title: "PDFConvertMagic - Free PDF Converter"
description: "Free online PDF converter. Convert PDF to Word, Excel, JPG and vice versa."
baseurl: ""
url: "https://pdfmagic.github.io"
theme: jekyll-theme-minimal
github:
  is_project_page: false
  show_downloads: false
plugins:
  - jekyll-sitemap
